import { FieldGroup } from "../models/business.model";

export const BusinessFieldGroup: FieldGroup = {
  title: "Add Your Business",
  id: "addBusinessForm",
  fields: [
    {
      id: "company",
      label: "Company",
      placeholder: "Company",
      type: "TEXT",
      required: false,
      value: "",
      readOnly: false,
      hidden: false,
    },
    {
      id: "streetAddress",
      label: "Street Address",
      placeholder: "Street Address",
      type: "TEXT",
      required: false,
      value: "",
      readOnly: false,
      hidden: false,
    },

    {
      id: "city",
      label: "City",
      placeholder: "City",
      type: "TEXT",
      required: false,
      value: "",
      readOnly: false,
      hidden: false,
    },
    {
      id: "state",
      label: "State",
      placeholder: "State",
      type: "TEXT",
      required: false,
      value: "",
      readOnly: false,
      hidden: false,
    },

    {
      id: "country",
      label: "Country",
      placeholder: "Country",
      type: "TEXT",
      required: false,
      value: "",
      readOnly: false,
      hidden: false,
    },

    {
      id: "code",
      label: "Zip/Postal Code",
      placeholder: "Zip/ Postal Code",
      type: "TEXT",
      required: false,
      value: "",
      readOnly: false,
      hidden: false,
    },

    {
      id: "mobile",
      label: "Mobile",
      placeholder: "Mobile",
      type: "TEXT",
      required: false,
      value: "",
      readOnly: false,
      hidden: false,
    },

    {
      id: "phone",
      label: "Phone",
      placeholder: "Phone",
      type: "TEXT",
      required: false,
      value: "",
      readOnly: false,
      hidden: false,
    },

    {
      id: "gst",
      label: "GST",
      placeholder: "GST",
      type: "TEXT",
      required: false,
      value: "",
      readOnly: false,
      hidden: false,
    },
    {
      id: "tc",
      label: "Terms & Instructions",
      placeholder: "Terms & Instructions",
      type: "TEXT",
      required: false,
      value: "",
      readOnly: false,
      hidden: false,
    },
    {
      id: "remarks",
      label: "Remarks/ Notes/ Payment Instructions",
      placeholder: "Remarks/ Notes/ Payment Instructions",
      type: "TEXT",
      required: false,
      value: "",
      readOnly: false,
      hidden: false,
    },
  ],
};
